# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
